# Generated by Django 4.1.2 on 2022-11-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='latitude',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='longitude',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
    ]
