# Generated by Django 4.1.2 on 2022-11-09 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0003_userprofile_latitude_userprofile_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='longitude',
        ),
    ]
